name: Run Backend API Tests

on: [pull_request]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.after }}

      - name: Get Commit Message
        run: |
          echo "MSG=$(git log --format=%B -n 1 ${{github.event.after}})" >> $GITHUB_ENV
      - name: Install Commitizen
        run: pip install -U Commitizen

      - name: Check For Valid Commit Message
        run: cz check -m "${{env.MSG }}"

      - name: Checking Commitizen Works
        run: cz version -p

      - name: Set Version
        run: |
          echo "COMMITIZEN_VER=$(cz version -p)" >> $GITHUB_ENV
        id: commitizen-version

      - name: Echo Current Version
        run: |
          echo "The current version is: ${{ env.COMMITIZEN_VER }}"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run: flake8 --show-source --statistics

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Setup Docker and Run Tests
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PGADMIN_EMAIL: ${{ secrets.PGADMIN_EMAIL }}
          PGADMIN_PASSWORD: ${{ secrets.PGADMIN_PASSWORD }}
          X_TOKEN: ${{ secrets.X_TOKEN }}
        run: |
          docker-compose -f docker-compose-test.yml build
          docker-compose -f docker-compose-test.yml run test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: true

      - name: Stop and remove Docker containers
        if: always()
        run: docker-compose -f docker-compose-test.yml down -v
